services:
  - type: web
    name: irc-hispano-client
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: IRC_HOST
        value: irc.irc-hispano.org
      - key: IRC_PLAIN_PORTS
        value: 6667,6668,6669,7000
      - key: IRC_SSL_PORTS
        value: 6697,7070
